In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('movies.csv')

In [3]:
df.head()

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime
0,The Shining,R,Drama,1980,"June 13, 1980 (United States)",8.4,927000.0,Stanley Kubrick,Stephen King,Jack Nicholson,United Kingdom,19000000.0,46998772.0,Warner Bros.,146.0
1,The Blue Lagoon,R,Adventure,1980,"July 2, 1980 (United States)",5.8,65000.0,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,United States,4500000.0,58853106.0,Columbia Pictures,104.0
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,"June 20, 1980 (United States)",8.7,1200000.0,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000.0,538375067.0,Lucasfilm,124.0
3,Airplane!,PG,Comedy,1980,"July 2, 1980 (United States)",7.7,221000.0,Jim Abrahams,Jim Abrahams,Robert Hays,United States,3500000.0,83453539.0,Paramount Pictures,88.0
4,Caddyshack,R,Comedy,1980,"July 25, 1980 (United States)",7.3,108000.0,Harold Ramis,Brian Doyle-Murray,Chevy Chase,United States,6000000.0,39846344.0,Orion Pictures,98.0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7668 entries, 0 to 7667
Data columns (total 15 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      7668 non-null   object
 1   rating    7591 non-null   object
 2   genre     7668 non-null   object
 3   year      7668 non-null   int64
 4   released  7666 non-null   object
 5   score     7665 non-null   float64
 6   votes     7665 non-null   float64
 7   director  7668 non-null   object
 8   writer    7665 non-null   object
 9   star      7667 non-null   object
 10  country   7665 non-null   object
 11  budget    5497 non-null   float64
 12  gross     7479 non-null   float64
 13  company   7651 non-null   object
 14  runtime   7664 non-null   float64
dtypes: float64(5), int64(1), object(9)
memory usage: 898.7+ KB

In [5]:
df.isnull().sum()

name           0
rating        77
genre          0
year           0
released       2
score          3
votes          3
director       0
writer         3
star           1
country        3
budget      2171
gross        189
company       17
runtime        4
dtype: int64

In [7]:
df.describe()

,year,score,votes,budget,gross,runtime
count,7668.000000,7665.000000,7.665000e+03,5.497000e+03,7.479000e+03,7664.000000
mean,2000.405451,6.390411,8.810850e+04,3.558988e+07,7.850054e+07,107.261613
std,11.153508,0.968842,1.633238e+05,4.145730e+07,1.657251e+08,18.581247
min,1980.000000,1.900000,7.000000e+00,3.000000e+03,3.090000e+02,55.000000
25%,1991.000000,5.800000,9.100000e+03,1.000000e+07,4.532056e+06,95.000000
50%,2000.000000,6.500000,3.300000e+04,2.050000e+07,2.020576e+07,104.000000
75%,2010.000000,7.100000,9.300000e+04,4.500000e+07,7.601669e+07,116.000000
max,2020.000000,9.300000,2.400000e+06,3.560000e+08,2.847246e+09,366.000000

In [8]:
df['name'].nunique()

7512

In [15]:
# Checking if any rows are duplicated --> no rows are duplicated
df.duplicated().sum()

0

In [9]:
# Made a new column named country by taking countries from the released columns 
df['country'] = df['released'].str.extract(r'\(([^)]+)\)')

In [10]:
df.head()

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime
0,The Shining,R,Drama,1980,"June 13, 1980 (United States)",8.4,927000.0,Stanley Kubrick,Stephen King,Jack Nicholson,United States,19000000.0,46998772.0,Warner Bros.,146.0
1,The Blue Lagoon,R,Adventure,1980,"July 2, 1980 (United States)",5.8,65000.0,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,United States,4500000.0,58853106.0,Columbia Pictures,104.0
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,"June 20, 1980 (United States)",8.7,1200000.0,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000.0,538375067.0,Lucasfilm,124.0
3,Airplane!,PG,Comedy,1980,"July 2, 1980 (United States)",7.7,221000.0,Jim Abrahams,Jim Abrahams,Robert Hays,United States,3500000.0,83453539.0,Paramount Pictures,88.0
4,Caddyshack,R,Comedy,1980,"July 25, 1980 (United States)",7.3,108000.0,Harold Ramis,Brian Doyle-Murray,Chevy Chase,United States,6000000.0,39846344.0,Orion Pictures,98.0

In [12]:
# dropped released columns as we have the year from the year column and country from the country column 
df.drop('released', axis=1, inplace=True)

In [13]:
df.head()

,name,rating,genre,year,score,votes,director,writer,star,country,budget,gross,company,runtime
0,The Shining,R,Drama,1980,8.4,927000.0,Stanley Kubrick,Stephen King,Jack Nicholson,United States,19000000.0,46998772.0,Warner Bros.,146.0
1,The Blue Lagoon,R,Adventure,1980,5.8,65000.0,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,United States,4500000.0,58853106.0,Columbia Pictures,104.0
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,8.7,1200000.0,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000.0,538375067.0,Lucasfilm,124.0
3,Airplane!,PG,Comedy,1980,7.7,221000.0,Jim Abrahams,Jim Abrahams,Robert Hays,United States,3500000.0,83453539.0,Paramount Pictures,88.0
4,Caddyshack,R,Comedy,1980,7.3,108000.0,Harold Ramis,Brian Doyle-Murray,Chevy Chase,United States,6000000.0,39846344.0,Orion Pictures,98.0

In [16]:
df.tail()

,name,rating,genre,year,score,votes,director,writer,star,country,budget,gross,company,runtime
7663,More to Life,NaN,Drama,2020,3.1,18.0,Joseph Ebanks,Joseph Ebanks,Shannon Bond,United States,7000.0,NaN,NaN,90.0
7664,Dream Round,NaN,Comedy,2020,4.7,36.0,Dusty Dukatz,Lisa Huston,Michael Saquella,United States,NaN,NaN,Cactus Blue Entertainment,90.0
7665,Saving Mbango,NaN,Drama,2020,5.7,29.0,Nkanya Nkwai,Lynno Lovert,Onyama Laura,Cameroon,58750.0,NaN,Embi Productions,NaN
7666,It's Just Us,NaN,Drama,2020,NaN,NaN,James Randall,James Randall,Christina Roz,United States,15000.0,NaN,NaN,120.0
7667,Tee em el,NaN,Horror,2020,5.7,7.0,Pereko Mosia,Pereko Mosia,Siyabonga Mabaso,United States,NaN,NaN,PK 65 Films,102.0

In [ ]:
def decade(row):
    if (row['year'] >= 1980) & (row['year'] < 1990):
        return '80s'
    elif (row['year'] >= 1990) & (row['year'] < 2000):
        return '90s'
    elif (row['year'] >= 2000) & (row['year'] < 2010):
        return '0s'
    else:
        return '10s'

In [56]:
def decades(row):
    if (row['year'] >= 1980) & (row['year'] < 1990):
        return '80s'
    elif (row['year'] >= 1990) & (row['year'] < 2000):
        return '90s'
    elif (row['year'] >= 2000) & (row['year'] < 2010):
        return '0s'
    else:
        return '10s'

In [57]:
df['decade'] = df.apply(decades, axis=1)

In [59]:
df.head()

,name,rating,genre,year,score,votes,director,writer,star,country,budget,gross,company,runtime,decade
0,The Shining,R,Drama,1980,8.4,927000.0,Stanley Kubrick,Stephen King,Jack Nicholson,United States,19000000.0,46998772.0,Warner Bros.,146.0,80s
1,The Blue Lagoon,R,Adventure,1980,5.8,65000.0,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,United States,4500000.0,58853106.0,Columbia Pictures,104.0,80s
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,8.7,1200000.0,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000.0,538375067.0,Lucasfilm,124.0,80s
3,Airplane!,PG,Comedy,1980,7.7,221000.0,Jim Abrahams,Jim Abrahams,Robert Hays,United States,3500000.0,83453539.0,Paramount Pictures,88.0,80s
4,Caddyshack,R,Comedy,1980,7.3,108000.0,Harold Ramis,Brian Doyle-Murray,Chevy Chase,United States,6000000.0,39846344.0,Orion Pictures,98.0,80s

In [74]:
dropped_rows = df[df['year'] == 2020].index

In [68]:
dropped_rows

,name,rating,genre,year,score,votes,director,writer,star,country,budget,gross,company,runtime,decade
7643,Tenet,PG-13,Action,2020,7.4,387000.0,Christopher Nolan,Christopher Nolan,John David Washington,United States,205000000.0,363656624.0,Warner Bros.,150.0,10s
7644,Wonder Woman 1984,PG-13,Action,2020,5.4,217000.0,Patty Jenkins,Patty Jenkins,Gal Gadot,United States,NaN,166534027.0,Atlas Entertainment,151.0,10s
7645,Birds of Prey,R,Action,2020,6.1,190000.0,Cathy Yan,Christina Hodson,Margot Robbie,United States,84500000.0,201858461.0,Clubhouse Pictures (II),109.0,10s
7646,The Invisible Man,R,Drama,2020,7.1,186000.0,Leigh Whannell,Leigh Whannell,Elisabeth Moss,United States,7000000.0,143151000.0,Universal Pictures,124.0,10s
7647,Onward,PG,Animation,2020,7.4,120000.0,Dan Scanlon,Dan Scanlon,Tom Holland,United States,NaN,141950608.0,Walt Disney Pictures,102.0,10s
7648,Bad Boys for Life,R,Action,2020,6.6,140000.0,Adil El Arbi,Peter Craig,Will Smith,United States,90000000.0,426505244.0,Columbia Pictures,124.0,10s
7649,Sonic the Hedgehog,PG,Action,2020,6.5,102000.0,Jeff Fowler,Pat Casey,Ben Schwartz,United States,85000000.0,319715683.0,Paramount Pictures,99.0,10s
7650,Dolittle,PG,Adventure,2020,5.6,53000.0,Stephen Gaghan,Stephen Gaghan,Robert Downey Jr.,United States,175000000.0,245487753.0,Universal Pictures,101.0,10s
7651,The Call of the Wild,PG,Adventure,2020,6.8,42000.0,Chris Sanders,Michael Green,Harrison Ford,United States,135000000.0,111105497.0,20th Century Studios,100.0,10s
7652,The Eight Hundred,Not Rated,Action,2020,6.8,3700.0,Hu Guan,Hu Guan,Zhi-zhong Huang,United States,80000000.0,461421559.0,Beijing Diqi Yinxiang Entertainment,149.0,10s
7653,The Quarry,R,Crime,2020,5.4,2400.0,Scott Teems,Scott Teems,Shea Whigham,Mexico,NaN,3661.0,Prowess Pictures,98.0,10s
7654,Star Trek First Frontier,NaN,Sci-Fi,2020,5.7,165.0,Kenneth Smith,Keith Brooks,Robert Pralgo,United States,370000.0,NaN,An Impulsive Production,85.0,10s
7655,Legend of Deification,TV-PG,Animation,2020,6.6,1300.0,Teng Cheng,NaN,Guangtao Jiang,United States,NaN,240663149.0,Beijing Enlight Pictures,110.0,10s
7656,Tulsa,PG-13,Comedy,2020,5.0,294.0,Scott Pryor,Scott Pryor,Scott Pryor,United States,NaN,413378.0,Pryor Entertainment,120.0,10s
7657,Leap,NaN,Drama,2020,6.7,903.0,Peter Ho-Sun Chan,Ji Zhang,Gong Li,United States,NaN,25818882.0,NaN,135.0,10s
7658,Black Wall Street Burning,R,Drama,2020,6.6,35.0,Marcus Brown,Dekoven Riggins,Dan Belcher,United States,5000.0,NaN,Notis Studio,78.0,10s
7659,I Am Fear,Not Rated,Horror,2020,3.4,447.0,Kevin Shulman,Kevin Shulman,Kristina Klebe,United States,NaN,13266.0,Roxwell Films,87.0,10s
7660,Aloha Surf Hotel,NaN,Comedy,2020,7.1,14.0,Stefan C. Schaefer,Stefan C. Schaefer,Augie Tulba,United States,NaN,NaN,Abominable Pictures,90.0,10s
7661,Love by Drowning,R,Drama,2020,NaN,NaN,Justin Kreinbrink,C.E. Poverman,Nicky Whelan,United States,1000000.0,NaN,Dow Jazz Films,121.0,10s
7662,The Robinsons,NaN,Action,2020,NaN,NaN,Directors,Aleks Alifirenko Jr.,Billy Hartmann,United States,10000.0,NaN,NaN,90.0,10s
7663,More to Life,NaN,Drama,2020,3.1,18.0,Joseph Ebanks,Joseph Ebanks,Shannon Bond,United States,7000.0,NaN,NaN,90.0,10s
7664,Dream Round,NaN,Comedy,2020,4.7,36.0,Dusty Dukatz,Lisa Huston,Michael Saquella,United States,NaN,NaN,Cactus Blue Entertainment,90.0,10s
7665,Saving Mbango,NaN,Drama,2020,5.7,29.0,Nkanya Nkwai,Lynno Lovert,Onyama Laura,Cameroon,58750.0,NaN,Embi Productions,NaN,10s
7666,It's Just Us,NaN,Drama,2020,NaN,NaN,James Randall,James Randall,Christina Roz,United States,15000.0,NaN,NaN,120.0,10s
7667,Tee em el,NaN,Horror,2020,5.7,7.0,Pereko Mosia,Pereko Mosia,Siyabonga Mabaso,United States,NaN,NaN,PK 65 Films,102.0,10s

In [77]:
df.drop(dropped_rows, axis=0, inplace=True)

In [78]:
df.tail()

,name,rating,genre,year,score,votes,director,writer,star,country,budget,gross,company,runtime,decade
7638,Chasing the Dragon II: Wild Wild Bunch,Not Rated,Action,2019,5.8,523.0,Jason Kwan,Koon-Nam Lui,Tony Ka Fai Leung,United States,NaN,45738461.0,Bona Film Group,101.0,10s
7639,Round of Your Life,NaN,Family,2019,4.6,150.0,Dylan Thomas Ellis,Tim Ogletree,Cole Allen,United States,NaN,20941.0,Aristar Entertainment,91.0,10s
7640,El Coyote,R,Action,2019,3.0,122.0,Jeffrey Nicholson,Jeffrey Nicholson,Michael Saquella,United States,NaN,1101470.0,Cactus Blue Entertainment,93.0,10s
7641,By Light of Desert Night,NaN,Drama,2019,4.8,373.0,David Stuart Snell,David Stuart Snell,Alexandra Bokova,United States,NaN,NaN,Canyon Media,94.0,10s
7642,A Brother's Love,NaN,Drama,2019,6.8,869.0,Monia Chokri,Monia Chokri,Anne-Élisabeth Bossé,Canada,NaN,1671969.0,Metafilms,117.0,10s